/*You are given two strings s and t.

String t is generated by random shuffling string s
and then add one more letter at a random position.

Return the letter that was added to t.*/

#include <string>
#include <algorithm>
using namespace std;

class Solution
{
public:
    char findTheDifference(string s, string t)
    {
        sort(s.begin(), s.end());
        sort(t.begin(), t.end());

        // Compare sorted strings
        for (int i = 0; i < s.length(); ++i)
        {
            if (s[i] != t[i])
            {
                return t[i]; // Return the different character
            }
        }

        // If no difference found, the extra character is at the end of `t`
        return t[t.length() - 1];
    }
};
